module.exports = {
    version: '>=0.7.7',
    type: 'library',
    name: 'kubevue-ui',
    CamelName: 'KubevueUI',
    lint: true,
    uglifyJS: true,
    extractCSS: true,
    sourceMap: true,
    webpackDevServer: {
        historyApiFallback: {
            index: '/kubevue-ui/',
        },
    },
    docs: {
        title: 'Kubevue UI Component Library',
        logo: 'Component Library',
        mode: 'history',
        base: '/kubevue-ui/',
        install: 'option-name',
        navbar: [
            { text: 'Guide', to: '/guide' },
            { text: 'Components', to: '/components' },
            { text: 'Demo', to: '/demo' },
        ],
        components: [
            { group: 'Basic', name: 'base', alias: 'Basic', path: 'proto-ui.kubevue/src/base/README.md' },
            { group: 'Basic', name: 'scheme', alias: 'Design specification', path: 'library/base/SCHEME.md' },
            { group: 'Basic', name: 'typography', alias: 'typography', path: 'proto-ui.kubevue/src/base/TYPOGRAPHY.md' },
            { group: 'Basic', name: 'u-text', alias: 'text' },
            { group: 'Basic', name: 'u-link', alias: 'link' },
            { group: 'Basic', name: 'u-button', alias: 'button' },
            { group: 'Basic', name: 'u-badge', alias: 'badge' },
            { group: 'Basic', name: 'u-label', alias: 'label', path: 'cloud-ui.kubevue/src/u-label.vue/README.md' },
            { group: 'Basic', name: 'u-tags', alias: 'tag group', path: 'cloud-ui.kubevue/src/u-tag.vue/README.md' },
            { group: 'Basic', name: 'u-icon', alias: 'icon', path: 'i-line-awesome.vue/README.md' },
            { group: 'Basic', name: 'u-status-icon', alias: 'status icon' },
            { group: 'Basic', name: 'u-logo', alias: 'logo' },
            { group: 'Layout', name: 'u-linear-layout', alias: 'linear layout' },
            { group: 'Layout', name: 'u-grid-layout', alias: 'Grid Layout' },
            { group: 'Layout', name: 'u-desc-list', alias: 'Description List', path: 'cloud-ui.kubevue/src/u-desc-list.vue/README.md' },
            { group: 'Layout', name: 'u-info-list', alias: 'Details list', path: 'cloud-ui.kubevue/src/u-info-list.vue/README.md' },
            { group: 'Layout', name: 'u-table', alias: 'table' },
            { group: 'Navigation', name: 'u-navbar', alias: 'Navigation bar' },
            { group: 'Navigation', name: 'u-sidebar', alias: 'sidebar' },
            { group: 'Navigation', name: 'u-menu', alias: 'menu' },
            { group: 'Navigation', name: 'u-subnav', alias: 'sub-navigation', path: 'cloud-ui.kubevue/src/u-subnav.vue/README.md' },
            { group: 'Navigation', name: 'u-tabs', alias: 'tabs' },
            { group: 'Navigation', name: 'u-subtabs', alias: 'subtab', path: 'cloud-ui.kubevue/src/u-subtabs.vue/README.md' },
            { group: 'Navigation', name: 'u-steps', alias: 'step bar', path: 'proto-ui.kubevue/src/u-steps.vue/README.md' },
            { group: 'Navigation', name: 'u-crumb', alias: 'breadcrumb' },
            { group: 'Navigation', name: 'u-pagination', alias: 'page turner' },
            { group: 'Navigation', name: 'u-actions', alias: 'action list' },
            { group: 'Form', name: 'u-form', alias: 'form', path: 'cloud-ui.kubevue/src/u-form.vue/README.md' },
            { group: 'Form', name: 'u-input', alias: 'Single line input', path: 'cloud-ui.kubevue/src/u-input.vue/README.md' },
            { group: 'Form', name: 'u-number-input', alias: 'numeric input' },
            { group: 'Form', name: 'u-textarea', alias: 'Multi-line input', path: 'cloud-ui.kubevue/src/u-textarea.vue/README.md' },
            { group: 'Form', name: 'u-radios', alias: 'radio group' },
            { group: 'Form', name: 'u-checkboxes', alias: 'Multi-select group' },
            { group: 'Form', name: 'u-switch', alias: 'switch', path: 'cloud-ui.kubevue/src/u-switch.vue/README.md' },
            { group: 'Form', name: 'u-select', alias: 'select box', path: 'cloud-ui.kubevue/src/u-select.vue/README.md' },
            { group: 'Form', name: 'u-cascade-select', alias: 'cascade-select' },
            { group: 'Form', name: 'u-region-select', alias: 'region selection' },
            { group: 'Form', name: 'u-multi-select', alias: 'Multiple Selection', path: 'cloud-ui.kubevue/src/u-multi-select.vue/README.md' },
            { group: 'Form', name: 'u-color-select', alias: 'Color selection', path: 'cloud-ui.kubevue/src/u-color-select.vue/README.md' },
            { group: 'Form', name: 'u-suggest', alias: 'auto-suggest', path: 'cloud-ui.kubevue/src/u-suggest.vue/README.md' },
            { group: 'Form', name: 'u-slider', alias: 'slider' },
            { group: 'Form', name: 'u-combo-slider', alias: 'Composite Slider', path: 'cloud-ui.kubevue/src/u-combo-slider.vue/README.md' },
            { group: 'Form', name: 'u-uploader', alias: 'File upload' },
            { group: 'Data', name: 'u-list-view', alias: 'list selection' },
            { group: 'Data', name: 'u-tree-view', alias: 'tree selection' },
            { group: 'Data', name: 'u-table-view', alias: 'table view', path: 'cloud-ui.kubevue/src/u-table-view.vue/README.md' },
            { group: 'Data', name: 'u-table-view-2', alias: 'table view 2' },
            { group: 'Data', name: 'u-capsules', alias: 'capsules', path: 'cloud-ui.kubevue/src/u-capsules.vue/README.md' },
            { group: 'Data', name: 'u-cascade-capsules', alias: 'cascade capsule', path: 'cloud-ui.kubevue/src/u-cascade-capsules.vue/README.md' },
            { group: 'Data', name: 'u-pills', alias: 'pills', path: 'cloud-ui.kubevue/src/u-pills.vue/README.md' },
            { group: 'Data', name: 'u-tablets', alias: 'tablets', path: 'cloud-ui.kubevue/src/u-tablets.vue/README.md' },
            { group: 'Data', name: 'u-transfer', alias: 'shuttle box' },
            { group: 'Data', name: 'u-countup', alias: 'numeric gradient' },
            { group: 'DateTime', name: 'u-calendar', alias: 'calendar', path: 'cloud-ui.kubevue/src/u-calendar.vue/README.md' },
            { group: 'DateTime', name: 'u-time-picker', alias: 'Date selection', path: 'cloud-ui.kubevue/src/u-time-picker.vue/README.md' },
            { group: 'DateTime', name: 'u-date-picker', alias: 'Time selection', path: 'cloud-ui.kubevue/src/u-date-picker.vue/README.md' },
            { group: 'DateTime', name: 'u-date-time-picker', alias: 'Period time selection', path: 'cloud-ui.kubevue/src/u-date-time-picker.vue/README. md' },
            { group: 'Popper', name: 'u-popper', alias: 'pop-up layer' },
            { group: 'Popper', name: 'u-popup', alias: 'pop-up box' },
            { group: 'Popper', name: 'u-tooltip', alias: 'Tooltip' },
            { group: 'Feedback', name: 'u-spinner', alias: 'Loading icon' },
            { group: 'Feedback', name: 'u-loading', alias: 'Loading' },
            { group: 'Feedback', name: 'u-placeholder', alias: 'placeholder' },
            { group: 'Feedback', name: 'u-toast', alias: 'Toast Tip' },
            { group: 'Feedback', name: 'u-modal', alias: 'pop-up', path: 'cloud-ui.kubevue/src/u-modal.vue/README.md' },
            { group: 'Feedback', name: 'u-lightbox', alias: 'Lightbox', path: 'cloud-ui.kubevue/src/u-lightbox.vue/README.md' },
            { group: 'Progress & Charts', name: 'u-linear-progress', alias: 'Linear Progress Bar', path: 'cloud-ui.kubevue/src/u-linear-progress.vue/README.md' },
            { group: 'Progress & Charts', name: 'u-circular-progress', alias: 'circular progress bar', path: 'cloud-ui.kubevue/src/u-circular-progress.vue/README.md' },
            { group: 'Progress & Charts', name: 'u-water-progress', alias: 'Water amount progress bar' },
            { group: 'Progress & Charts', name: 'u-chart', alias: 'Chart base class' },
            { group: 'Progress & Charts', name: 'u-bar-chart', alias: 'Bar chart', path: 'cloud-ui.kubevue/src/u-bar-chart.vue/README.md' } ,
            { group: 'Progress & Charts', name: 'u-xbar-chart', alias: 'Horizontal bar chart', path: 'cloud-ui.kubevue/src/u-xbar-chart.vue/README.md' },
            { group: 'Progress & Charts', name: 'u-line-chart', alias: 'line chart' },
            { group: 'Progress & Charts', name: 'u-pie-chart', alias: 'pie chart' },
            { group: 'Progress & Charts', name: 'u-donut-chart', alias: 'donut chart' },
            // { group: 'Extension', name: 'x-ace-editor', alias: 'Code Editor', path: 'x-ace-editor.vue/README.md' },
            { group: 'Mixin & Utils', name: 'u-emitter', alias: 'trigger' },
            { group: 'Mixin & Utils', name: 'u-router-item', alias: 'Route item' },
            { group: 'Mixin & Utils', name: 'u-collapse-transition', alias: 'collapse transition' },
            { group: 'Mixin & Utils', name: 'u-draggable', alias: 'drag' },
            { group: 'Mixin & Utils', name: 'u-droppable', alias: 'drag-and-drop' },
            { group: 'Mixin & Utils', name: 'u-dragger', alias: 'dragger' },
        ],
    },
};
